finder_base:
    #Publish all the joint states------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    #Position controllers--------------------------------
    right_front_flipper_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_front_flipper_joint
        pid: {p: 30.0, i: 30.0, d: 5.0}
    left_front_flipper_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_front_flipper_joint
        pid: {p: 30.0, i: 30.0, d: 5.0}
    right_back_flipper_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_back_flipper_joint
        pid: {p: 30.0, i: 30.0, d: 5.0}
    left_back_flipper_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_back_flipper_joint
        pid: {p: 30.0, i: 30.0, d: 5.0}
